'use strict';

const path = require('path');

const express = require('express');
const viewEngine = require('ejs-locals');
const minify = require('html-minifier').minify;

const app = express();

// Server Config ==========================================

app.engine('ejs', viewEngine);
app.set('views', path.join(__dirname, '../views'));
app.set('view engine', 'ejs');

app.use(express.static(path.join(__dirname, '../statics')));

app.use(function (req, res, next) {
    res.send_my = res.send;
    res.send = (body) => {
        if (typeof body == 'string') {
            try {
                let contentType = res.get('content-type');
                if (!contentType || contentType === 'text/html') {
                    let result = minify(body, {
                        collapseInlineTagWhitespace: true,
                        collapseWhitespace: true,
                        includeAutoGeneratedTags: true,
                        minifyCSS: true,
                        minifyJS: true,
                        minifyURLs: true,
                        removeComments: true,
                        removeEmptyAttributes: true,
                        sortAttributes: true,
                        sortClassName: true,
                    });
        
                    return res.send_my(result);
                } else {
                    return res.send_my(body);
                }
                
            }
            catch (err) {
                console.log(err);
            }
        }

        res.send_my(body);
    }

    next();
});

app.use(function (err, req, res, next) {
    console.log(err);

    res.status(err.status || 500);
    res.end();
});

const imageRoute = require('../routes/images.js');
const humanRoute = require('../routes/human.js');
const movieRoute = require('../routes/movie.js');
const apiRoute = require('../routes/api.js');

// ========================================================

app.use('/images', imageRoute);
app.use('/human', humanRoute);
app.use('/movie', movieRoute);
app.use('/api', apiRoute);

app.all('/', (req, res) => {
    res.redirect('https://www.google.com');
});

// Config for development =====================================================
if ( app.get('env') === 'development' ) {
    app.set('port', (process.env.PORT || 3000));
}

// Config for development =====================================================
if ( app.get('env') === 'production' ) {
    app.set('port', (process.env.PORT || 80));
}

module.exports = app;
